version: "3.9"
services:
  snyk-broker:
    hostname: broker
    image: snyk/broker:github-enterprise
    restart: always
    ports:
      - "8000:8000"
    environment:
    - BROKER_TOKEN=secret-broker-token
    - GITHUB_TOKEN=secret-github-token
    - GITHUB=your.ghe.domain.com 
    - GITHUB_API=your.ghe.domain.com/api/v3 
    - GITHUB_GRAPHQL=your.ghe.domain.com/api
    - BROKER_CLIENT_URL=http://my.broker.client:8000
    - CA_CERT=/private/ca.cert.pem
    - PORT=8000
    - GIT_CLIENT_URL=http://code-agent:3000
    - ACCEPT=/private/accept.json
    volumes:
      - /local/path/to/private:/private

  snyk-agent:
    hostname: code-agent
    image: snyk/code-agent
    restart: always
    ports:
      - "3000:3000"
    environment:
    - SNYK_TOKEN=snyk-api-token
    - PORT=3000