#  Example pipeline to test Serverless Framework with Snyk IaC

image: node:latest

pipelines:
  default:
    - step:
        name: Setup Snyk and Serverless - then run and test
        caches:
          - node
        script:
          - npm install snyk -g
          - npm install -g serverless
          - snyk auth $SNYK_AUTH
          # Serverless has to run on the same folder as the serverless.yml
          # e.g. - cd iac/serverless
          - serverless package --package serverless-artifacts 
          # You can go back to the root folder to scan other IaC
          # e.g. - cd ../..
          - snyk iac test || true # Remove || true to fail on vulnerabilities
          # - snyk iac test --json || true > results.json # To export results as a .json

